#!/usr/bin/env bash
# setup-wg-sudoers.sh — Install the scoped sudoers rule that lets the
# unprivileged ``hobeproxy`` service user invoke ``wg`` for ONLY the two
# operations the zero-touch peer reconciler needs:
#
#   wg show wg-data dump
#   wg set wg-data peer <PUBKEY> allowed-ips <CIDR[,CIDR…]>
#   wg set wg-data peer <PUBKEY> remove
#
# Nothing else. The reconciler cannot bring the interface up, cannot
# overwrite the private key, cannot listen on a port, cannot run `wg`
# against another interface. This is the smallest grant that still gives
# us zero-touch sync.
#
# Install once per proxy host:
#
#     sudo bash systemd/setup-wg-sudoers.sh
#
# Then set in /etc/hobe-radius-proxy/env (if not already):
#
#     PROXY_WG_BIN=/usr/local/sbin/hobe-wg
#     PROXY_WG_PEER_SYNC_ENABLED=true
#
# and `systemctl restart radius-proxy`.
#
# Idempotent — safe to re-run on every deploy.
set -euo pipefail

SERVICE_USER="${PROXY_SERVICE_USER:-hobeproxy}"
WG_BIN="${WG_BIN:-/usr/bin/wg}"
WRAPPER="/usr/local/sbin/hobe-wg"
SUDOERS_FILE="/etc/sudoers.d/hobe-radius-proxy-wg"

if [[ $EUID -ne 0 ]]; then
    echo "setup-wg-sudoers: must run as root (try: sudo bash $0)" >&2
    exit 1
fi

if ! command -v "$WG_BIN" >/dev/null 2>&1; then
    echo "setup-wg-sudoers: '$WG_BIN' not installed — run: apt -y install wireguard-tools" >&2
    exit 1
fi

if ! id -u "$SERVICE_USER" >/dev/null 2>&1; then
    echo "setup-wg-sudoers: user '$SERVICE_USER' does not exist; create the proxy service user first." >&2
    exit 1
fi

# ── 1. Scoped sudoers rule. ───────────────────────────────────────────
# Each pattern uses sudo's wildcards (NOT shell globs) — wildcards match
# any single argv token but cannot reach across spaces. So `wg set wg-data
# peer *` cannot be abused to inject extra `--` flags or run a different
# subcommand.
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

cat > "$TMP" <<EOF
# Installed by setup-wg-sudoers.sh — DO NOT EDIT.
# Grants the radius-proxy service user the minimum 'wg' invocations
# required by the zero-touch peer sync reconcilers — both the wg-data
# (CHR ↔ proxy) and wg-radius (customer ↔ proxy) interfaces. Nothing else.

# wg-data — CHR fleet plane (existing).
Cmnd_Alias HOBE_WG_SHOW_DATA = $WG_BIN show wg-data dump
Cmnd_Alias HOBE_WG_SET_DATA  = $WG_BIN set wg-data peer * allowed-ips *, \\
                               $WG_BIN set wg-data peer * remove

# wg-radius — customer RADIUS plane (new, design §4.2).
Cmnd_Alias HOBE_WG_SHOW_RADIUS = $WG_BIN show wg-radius dump
Cmnd_Alias HOBE_WG_SET_RADIUS  = $WG_BIN set wg-radius peer * allowed-ips *, \\
                                 $WG_BIN set wg-radius peer * remove

$SERVICE_USER ALL=(root) NOPASSWD: HOBE_WG_SHOW_DATA, HOBE_WG_SET_DATA, \\
                                   HOBE_WG_SHOW_RADIUS, HOBE_WG_SET_RADIUS
Defaults!HOBE_WG_SHOW_DATA,HOBE_WG_SET_DATA,HOBE_WG_SHOW_RADIUS,HOBE_WG_SET_RADIUS !requiretty
EOF

# Validate before installing (visudo -c -f).
if ! visudo -c -f "$TMP" >/dev/null; then
    echo "setup-wg-sudoers: refusing to install — sudoers syntax check failed." >&2
    exit 1
fi

install -m 0440 -o root -g root "$TMP" "$SUDOERS_FILE"
echo "setup-wg-sudoers: installed $SUDOERS_FILE"

# ── 2. Tiny wrapper script that prepends `sudo -n` to every wg call. ─
# The proxy is then configured with PROXY_WG_BIN=/usr/local/sbin/hobe-wg.
cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
# Auto-generated by setup-wg-sudoers.sh. Forwards a constrained set of
# 'wg' invocations through sudo. The sudoers rule above pins which ones.
exec /usr/bin/sudo -n $WG_BIN "\$@"
EOF
chmod 0755 "$WRAPPER"
chown root:root "$WRAPPER"
echo "setup-wg-sudoers: installed $WRAPPER (proxy should set PROXY_WG_BIN=$WRAPPER)"

# ── 3. Smoke check (read-only). ───────────────────────────────────────
if sudo -u "$SERVICE_USER" "$WRAPPER" show wg-data dump >/dev/null 2>&1; then
    echo "setup-wg-sudoers: OK — $SERVICE_USER can invoke 'wg show wg-data dump'."
else
    echo "setup-wg-sudoers: WARNING — $SERVICE_USER could not run 'wg show wg-data dump'." >&2
    echo "  This is normal if wg-data isn't up yet; rerun after 'wg-quick up wg-data'." >&2
fi

# ── 4. Make sure the state directory exists + is writable. ───────────
install -d -m 0750 -o "$SERVICE_USER" -g "$SERVICE_USER" \
    /var/lib/hobe-radius-proxy
echo "setup-wg-sudoers: state dir /var/lib/hobe-radius-proxy ready (owner=$SERVICE_USER)."

echo "setup-wg-sudoers: done."
